version: "3"
services:
  # db:
  #   environment: 
  #     POSTGRES_DB: ${POSTGRES_DB}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PORT: ${POSTGRES_PORT}
  #   image: "postgres:11.5"
  #   ports:
  #     - "${POSTGRES_PORT}:5432"
  #   volumes:
  #     - ./db/pgdata:/pgdata
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: glennmeyer/gloomhaven-character-helper:latest
    ports:
      - "80:4200"
    volumes:
      - .:/web
    # logging:
    #     driver: awslogs
    #     options: 
    #       awslogs-group: gloomy
    #       awslogs-region: us-east-2
    #       awslogs-stream-prefix: web